/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HomePC
 */
public class Formpatient extends javax.swing.JFrame {

    /**
     * Creates new form Formpatient
     */
    public Formpatient() {
        initComponents();
        infoDemandes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTprenompat = new javax.swing.JTextField();
        jBsupprimer = new javax.swing.JButton();
        jLtelpat = new javax.swing.JLabel();
        jTtelpat = new javax.swing.JTextField();
        jLinfodem = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBenregistrer = new javax.swing.JButton();
        jBvisualiser = new javax.swing.JButton();
        jBinitialiser = new javax.swing.JButton();
        jLnompat = new javax.swing.JLabel();
        jBrechercher = new javax.swing.JButton();
        jTnompat = new javax.swing.JTextField();
        jTrechercher = new javax.swing.JTextField();
        jLprenompat = new javax.swing.JLabel();
        jBmodifier = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBsupprimer.setForeground(new java.awt.Color(255, 51, 51));
        jBsupprimer.setText("Supprimer");
        jBsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsupprimerActionPerformed(evt);
            }
        });

        jLtelpat.setText("Tél");

        jLinfodem.setText("ID demande");

        jBenregistrer.setForeground(new java.awt.Color(51, 255, 51));
        jBenregistrer.setText("Enregistrer");
        jBenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenregistrerActionPerformed(evt);
            }
        });

        jBvisualiser.setText("Visualiser");
        jBvisualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvisualiserActionPerformed(evt);
            }
        });

        jBinitialiser.setText("Initialiser");
        jBinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinitialiserActionPerformed(evt);
            }
        });

        jLnompat.setText("Nom");

        jBrechercher.setForeground(new java.awt.Color(0, 0, 204));
        jBrechercher.setText("Rechercher");
        jBrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrechercherActionPerformed(evt);
            }
        });

        jLprenompat.setText("Prénom");

        jBmodifier.setText("Modifier");
        jBmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodifierActionPerformed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(0, 51, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID patient", "Nom", "Prenom", "Tél", "ID demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBenregistrer)
                        .addGap(18, 18, 18)
                        .addComponent(jBvisualiser)
                        .addGap(18, 18, 18)
                        .addComponent(jBinitialiser)
                        .addGap(18, 18, 18)
                        .addComponent(jBmodifier)
                        .addGap(18, 18, 18)
                        .addComponent(jBsupprimer)
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLnompat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTnompat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLprenompat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTprenompat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLtelpat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTtelpat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLinfodem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBrechercher)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnompat)
                    .addComponent(jTnompat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLprenompat)
                    .addComponent(jTprenompat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtelpat)
                    .addComponent(jTtelpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLinfodem)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBenregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBvisualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Connection connect() {
    String url = "jdbc:mysql://localhost:3306/laboratoire_hopital_hope";
    String user = "root";
    String password = "";
    Connection conn = null;
    try {
        conn = DriverManager.getConnection(url, user, password);
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
    return conn;
}
private void infoDemandes() {
        String sql = "SELECT Id_demandes, Medecin_demandeur FROM Demandes";
        try (Connection conn = this.connect();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            while (rs.next()) {
                String idMeddemandeurDemande = rs.getInt("Id_demandes") + " / " + rs.getString("Medecin_demandeur");
                model.addElement(idMeddemandeurDemande);
            }
            jComboBox1.setModel(model);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
private void jjTable1MouseClicked() {                                         
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) { 
            jTnompat.setText(jTable1.getValueAt(selectedRow, 1).toString());
            jTprenompat.setText(jTable1.getValueAt(selectedRow, 2).toString());
            jTtelpat.setText(jTable1.getValueAt(selectedRow, 3).toString());
            jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString());
        }
    }
    private void jBenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenregistrerActionPerformed
        // TODO add your handling code here:
        enregistrerpatient();
    }//GEN-LAST:event_jBenregistrerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jjTable1MouseClicked();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBvisualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvisualiserActionPerformed
        // TODO add your handling code here:
        visualiserpatientData();
    }//GEN-LAST:event_jBvisualiserActionPerformed

    private void jBinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinitialiserActionPerformed
        // TODO add your handling code here:
        initialiserFields();
    }//GEN-LAST:event_jBinitialiserActionPerformed

    private void jBmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodifierActionPerformed
        // TODO add your handling code here:
        modifierpatient();
    }//GEN-LAST:event_jBmodifierActionPerformed

    private void jBsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsupprimerActionPerformed
        // TODO add your handling code here:
        supprimerpatient();
    }//GEN-LAST:event_jBsupprimerActionPerformed

    private void jBrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrechercherActionPerformed
        // TODO add your handling code here:
        rechercherpatient();
    }//GEN-LAST:event_jBrechercherActionPerformed
private void enregistrerpatient() {
    String sql = "INSERT INTO Patients(Nom, Prenom, Tel, Id_demandes) VALUES(?, ?, ?, ?)";

    try (Connection conn = this.connect();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, jTnompat.getText());
        pstmt.setString(2, jTprenompat.getText());
        pstmt.setString(3, jTtelpat.getText());
        
        String selectedEchantillon = jComboBox1.getSelectedItem().toString();
        String[] parts = selectedEchantillon.split(" ", 2); // Diviser en deux parties seulement
        int idechantillons = Integer.parseInt(parts[0].trim()); // Extraire l'ID
        pstmt.setInt(4, idechantillons);

        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Patient enregistré avec succès");

    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
}
private void visualiserpatientData() {
        String sql = "SELECT * FROM patients";
        
        try (Connection conn = this.connect();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("Id_patients"),
                    rs.getString("Nom"),
                    rs.getString("Prenom"),
                    rs.getInt("Tel"),
                    rs.getInt("Id_demandes"),
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des données : " + e.getMessage());
        }
    }
private void initialiserFields() {
        jTnompat.setText("");
        jTprenompat.setText("");
        jTtelpat.setText("");
        jComboBox1.setSelectedIndex(0);
    }
private void modifierpatient() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int Id_patients = (int) jTable1.getValueAt(selectedRow, 0);
            String sql = "UPDATE patients SET Nom = ?, Prenom = ?, Tel = ?, Id_demandes = ? WHERE Id_patients = ?";

            try (Connection conn = this.connect();
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, jTnompat.getText());
                pstmt.setString(2, jTprenompat.getText());
                pstmt.setString(3, jTtelpat.getText());
                
                String selectedDemande = jComboBox1.getSelectedItem().toString();
                String[] parts = selectedDemande.split(" ", 2);
                int idechantillons = Integer.parseInt(parts[0].trim());
                pstmt.setInt(4, idechantillons);
                
                pstmt.setInt(5, Id_patients);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Patient modifié avec succès");
                visualiserpatientData();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification des données : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un Patient à modifier");
        }
    }
private void supprimerpatient() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String echantillonsId = jTable1.getValueAt(selectedRow, 0).toString();
            String sql = "DELETE FROM patients WHERE Id_patients = ?";

            try (Connection conn = this.connect();
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, echantillonsId);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Patient supprimé avec succès");
                visualiserpatientData();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un Laborantin à supprimer");
        }
    }
private void  rechercherpatient() {
        String searchTerm = jTrechercher.getText();
        String sql = "SELECT * FROM patients WHERE  Nom LIKE ? OR Prenom LIKE ? OR Tel LIKE ? OR Id_demandes LIKE ?";
        
        try (Connection conn = this.connect();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            String searchPattern = "%" + searchTerm + "%";
            pstmt.setString(1, searchPattern);
            pstmt.setString(2, searchPattern);
            pstmt.setString(3, searchPattern);
            pstmt.setString(4, searchPattern);
             
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("Id_patients"),
                        rs.getString("Nom"),
                        rs.getString("Prenom"),
                        rs.getString("Tel"),
                        rs.getInt("Id_demandes"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formpatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBenregistrer;
    private javax.swing.JButton jBinitialiser;
    private javax.swing.JButton jBmodifier;
    private javax.swing.JButton jBrechercher;
    private javax.swing.JButton jBsupprimer;
    private javax.swing.JButton jBvisualiser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLinfodem;
    private javax.swing.JLabel jLnompat;
    private javax.swing.JLabel jLprenompat;
    private javax.swing.JLabel jLtelpat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTnompat;
    private javax.swing.JTextField jTprenompat;
    private javax.swing.JTextField jTrechercher;
    private javax.swing.JTextField jTtelpat;
    // End of variables declaration//GEN-END:variables
}
