/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;


/**
 *
 * @author HomePC
 */
public class Formechantillon extends javax.swing.JFrame {

    /**
     * Creates new form Formechantillon
     */
    public Formechantillon() {
        initComponents();
        infoDemandes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLmethprel = new javax.swing.JLabel();
        jTmethprel = new javax.swing.JTextField();
        jLdate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLtypeecha = new javax.swing.JLabel();
        jTtypeecha = new javax.swing.JTextField();
        jLinfodem = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBenregistrer = new javax.swing.JButton();
        jBvisualiser = new javax.swing.JButton();
        jBinitialiser = new javax.swing.JButton();
        jBmodifier = new javax.swing.JButton();
        jBsupprimer = new javax.swing.JButton();
        jBrechercher = new javax.swing.JButton();
        jTrechercher = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLmethprel.setText("Méthode de prélèvement");

        jLdate.setText("Date");

        jLtypeecha.setText("Type d'échantillon");

        jLinfodem.setText("ID demande");

        jBenregistrer.setForeground(new java.awt.Color(51, 255, 51));
        jBenregistrer.setText("Enregistrer");
        jBenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenregistrerActionPerformed(evt);
            }
        });

        jBvisualiser.setText("Visualiser");
        jBvisualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvisualiserActionPerformed(evt);
            }
        });

        jBinitialiser.setText("Initialiser");
        jBinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinitialiserActionPerformed(evt);
            }
        });

        jBmodifier.setText("Modifier");
        jBmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodifierActionPerformed(evt);
            }
        });

        jBsupprimer.setForeground(new java.awt.Color(255, 0, 0));
        jBsupprimer.setText("Supprimer");
        jBsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsupprimerActionPerformed(evt);
            }
        });

        jBrechercher.setForeground(new java.awt.Color(0, 0, 204));
        jBrechercher.setText("Rechercher");
        jBrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrechercherActionPerformed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(0, 51, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID échantillon", "Méthode de prélevement", "Date de prélèvement", "Type d'échantillon", "ID demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLmethprel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTmethprel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                .addComponent(jTrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLtypeecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTtypeecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLinfodem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBenregistrer)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBvisualiser)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBinitialiser)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBmodifier)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBsupprimer)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBrechercher)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLmethprel)
                    .addComponent(jTmethprel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLdate)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtypeecha)
                    .addComponent(jTtypeecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLinfodem)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBmodifier, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBinitialiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBenregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBvisualiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Connection connect() {
    String url = "jdbc:mysql://localhost:3306/laboratoire_hopital_hope";
    String user = "root";
    String password = "";
    Connection conn = null;
    try {
        conn = DriverManager.getConnection(url, user, password);
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
    return conn;
}
private void infoDemandes() {
        String sql = "SELECT Id_demandes, Medecin_demandeur FROM Demandes";
        try (Connection conn = this.connect();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            while (rs.next()) {
                String idMeddemandeurDemande = rs.getInt("Id_demandes") + " / " + rs.getString("Medecin_demandeur");
                model.addElement(idMeddemandeurDemande);
            }
            jComboBox1.setModel(model);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
private java.util.Date parseDate(String dateString) {
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    java.util.Date date = null;
    try {
        date = format.parse(dateString);
    } catch (ParseException e) {
        // Gestion simple : mettre la date à null en cas d'échec de parsing
        System.err.println("Erreur de parsing de la date: " + dateString);
    }
    return date;
}
private void jjTable1MouseClicked() {                                         
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) { 
            jTmethprel.setText(jTable1.getValueAt(selectedRow, 1).toString());
            String dateString = jTable1.getValueAt(selectedRow, 2).toString();
            java.util.Date date = parseDate(dateString);
           
            jDateChooser1.setDate(date);
            jTtypeecha.setText(jTable1.getValueAt(selectedRow, 3).toString());
            jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString());
        }
    }
    private void jBenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenregistrerActionPerformed
        // TODO add your handling code here:
        enregistrerdemande();
    }//GEN-LAST:event_jBenregistrerActionPerformed

    private void jBvisualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvisualiserActionPerformed
        // TODO add your handling code here:
        visualiserechantillonData();
    }//GEN-LAST:event_jBvisualiserActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jjTable1MouseClicked();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinitialiserActionPerformed
        // TODO add your handling code here:
        initialiserFields();
    }//GEN-LAST:event_jBinitialiserActionPerformed

    private void jBmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodifierActionPerformed
        // TODO add your handling code here:
        modifierechantillons();
    }//GEN-LAST:event_jBmodifierActionPerformed

    private void jBsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsupprimerActionPerformed
        // TODO add your handling code here:
        supprimerechantillon();
    }//GEN-LAST:event_jBsupprimerActionPerformed

    private void jBrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrechercherActionPerformed
        // TODO add your handling code here:
        rechercherechantillon();
    }//GEN-LAST:event_jBrechercherActionPerformed
private void enregistrerdemande() {
    String sql = "INSERT INTO echantillons(Methode_prelevement, Date_prelevement, Type_echa_prelever, Id_demandes) VALUES(?, ?, ?, ?)";

    try (Connection conn = this.connect();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, jTmethprel.getText());

        java.util.Date utilDate = jDateChooser1.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        pstmt.setDate(2, sqlDate);

        pstmt.setString(3, jTtypeecha.getText());

        String selectedDemande = jComboBox1.getSelectedItem().toString();
        String[] parts = selectedDemande.split(" ", 2); // Diviser en deux parties seulement
        int iddemandes = Integer.parseInt(parts[0].trim()); // Extraire l'ID
        pstmt.setInt(4, iddemandes);

        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Echantillon enregistré avec succès");

    } catch (SQLException e) {
        System.out.println(e.getMessage());
    } catch (NumberFormatException e) {
        System.out.println("Erreur de format de nombre pour l'ID : " + e.getMessage());
    }
}

private void visualiserechantillonData() {
        String sql = "SELECT * FROM echantillons";
        
        try (Connection conn = this.connect();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("Id_echantillons"),
                     rs.getString("Methode_prelevement"),
                    rs.getString("Date_prelevement"),
                    rs.getString("Type_echa_prelever"),
                    rs.getInt("Id_demandes"),
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des données : " + e.getMessage());
        }
    }
private void initialiserFields() {
        jTmethprel.setText("");
        jDateChooser1.setDate(null);
        jTtypeecha.setText("");
        jComboBox1.setSelectedIndex(0);
    }
private void modifierechantillons() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int Id_echantillons = (int) jTable1.getValueAt(selectedRow, 0);
            String sql = "UPDATE echantillons SET Methode_prelevement = ?, Date_prelevement = ?, Type_echa_prelever = ?, Id_demandes = ? WHERE Id_echantillons = ?";

            try (Connection conn = this.connect();
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, jTmethprel.getText());
                java.util.Date utilDate = jDateChooser1.getDate();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                pstmt.setDate(2, sqlDate);
                pstmt.setString(3, jTtypeecha.getText());
                
                String selectedDemande = jComboBox1.getSelectedItem().toString();
                String[] parts = selectedDemande.split(" ", 2);
                int iddemandes = Integer.parseInt(parts[0].trim());
                pstmt.setInt(4, iddemandes);
                
                pstmt.setInt(5, Id_echantillons);

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Echantillon modifiée avec succès");
                visualiserechantillonData();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification des données : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un échantillon à modifier");
        }
    }
 private void supprimerechantillon() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String echantillonsId = jTable1.getValueAt(selectedRow, 0).toString();
            String sql = "DELETE FROM echantillons WHERE Id_echantillons = ?";

            try (Connection conn = this.connect();
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, echantillonsId);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "échantillon supprimée avec succès");
                visualiserechantillonData();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un échantillon à supprimer");
        }
    }
 private void  rechercherechantillon() {
        String searchTerm = jTrechercher.getText();
        String sql = "SELECT * FROM echantillons WHERE Methode_prelevement LIKE ? OR Date_prelevement LIKE ? OR Type_echa_prelever LIKE ? OR Id_demandes LIKE ?";
        
        try (Connection conn = this.connect();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            String searchPattern = "%" + searchTerm + "%";
            pstmt.setString(1, searchPattern);
            pstmt.setString(2, searchPattern);
            pstmt.setString(3, searchPattern);
            pstmt.setString(4, searchPattern);
             
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("Id_echantillons"),
                        rs.getString("Methode_prelevement"),
                        rs.getString("Date_prelevement"),
                        rs.getString("Type_echa_prelever"),
                        rs.getInt("Id_demandes"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formechantillon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formechantillon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formechantillon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formechantillon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formechantillon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBenregistrer;
    private javax.swing.JButton jBinitialiser;
    private javax.swing.JButton jBmodifier;
    private javax.swing.JButton jBrechercher;
    private javax.swing.JButton jBsupprimer;
    private javax.swing.JButton jBvisualiser;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLdate;
    private javax.swing.JLabel jLinfodem;
    private javax.swing.JLabel jLmethprel;
    private javax.swing.JLabel jLtypeecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTmethprel;
    private javax.swing.JTextField jTrechercher;
    private javax.swing.JTextField jTtypeecha;
    // End of variables declaration//GEN-END:variables
}
